# Generated by Django 3.0.8 on 2020-07-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SkillType')),
            ],
        ),
    ]
