# Generated by Django 3.0.8 on 2020-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
