# Generated by Django 3.0.8 on 2020-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200725_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
