# Generated by Django 3.0.8 on 2020-07-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200725_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalproject',
            name='designation',
            field=models.CharField(max_length=50, verbose_name='Designation'),
        ),
    ]
