# Generated by Django 3.0.8 on 2020-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200725_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalproject',
            name='client',
            field=models.CharField(max_length=100, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='environment',
            field=models.CharField(max_length=200, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='responsibilities',
            field=models.TextField(verbose_name='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='team_size',
            field=models.IntegerField(verbose_name='Team Size'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
