# Generated by Django 3.0.8 on 2020-07-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200725_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='from_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='to_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='professionalproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company', verbose_name='Company'),
        ),
    ]
