# Generated by Django 3.0.8 on 2020-07-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200727_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalproject',
            name='designation',
        ),
    ]
