# Generated by Django 3.0.8 on 2020-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_professionalproject_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalproject',
            name='image',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Image'),
        ),
    ]
