# Generated by Django 3.0.8 on 2020-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_professionalproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.CharField(max_length=20, verbose_name='Image')),
                ('technology', models.CharField(max_length=200, verbose_name='Technology')),
                ('url', models.URLField(verbose_name='Url')),
                ('is_sc_enabled', models.BooleanField(default=False, verbose_name='Source Code Enabled')),
            ],
        ),
    ]
