# Generated by Django 3.0.8 on 2020-07-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hobbyproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalproject',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Image'),
        ),
    ]
